services:
  postgres:
    image: postgres:18
    expose:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "authentik", "-U", "authentik" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    network_mode: host
    restart: unless-stopped
